import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import pizzaPic from "../public/images/pizza_pic.jpg";
import groceryCombo from "../public/images/grocery_combo.jpg";
import Services from "../components/Services";
import ImageSlider from "../components/ImageSlider";
import Carousel from "../components/Carousel";

export default function Home() {
  const demoImages = [
    "https://images.unsplash.com/photo-1486485764572-92b96f21882a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGl6emElMjBwaWNzfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    "https://images.unsplash.com/photo-1528137871618-79d2761e3fd5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cGl6emElMjBwaWNzfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfDB8MHx8&auto=format&fit=crop&w=600&q=60",
  ];

  return (
    <main className="px-2">
      <Head>
        <title>MultiVen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* carousel featured section */}
      <ImageSlider images={demoImages} />

      {/* services section */}
      <Services />
      <hr className="border-[2px] mt-6" />
      {/* featured section */}
      <h2 className="text-2xl mt-4 font-semibold text-gray-700">
        Today's Specials
      </h2>
      <section className="grid grid-cols-2 mt-2">
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
      </section>
      <hr className="border-[2px] mt-6" />
      <h2 className="text-2xl mt-4 font-semibold text-gray-700">
        Grocery Combos
      </h2>
      <section className="grid grid-cols-2 mt-2">
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
      </section>
      <hr className="border-[2px] mt-6" />
      <h2 className="text-2xl mt-4 font-semibold text-gray-700">
        Popular Rentals
      </h2>
      <section className="grid grid-cols-2 mt-2">
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
        <div className="h-28 m-1 rounded-md bg-[#f87171]">hello</div>
      </section>
    </main>
  );
}
